version: '3'
services:
  aws:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "9093:9093"
    environment:
      - SERVICES=dynamodb,s3,sqs
      - DEBUG=true
      - DATA_DIR=/var/data/aws-data
      - PORT_WEB_UI=9093
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - database-data:/var/data/aws-data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - index-data:/usr/share/elasticsearch/data
      - ./cnf/es/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./cnf/es/jvm.options:/usr/share/elasticsearch/config/jvm.options.d/extra.options
      - ./cnf/es/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://index:9200
      ELASTICSEARCH_HOSTS: '["http://index:9200"]'
volumes:
  database-data:
  index-data: